[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cowsay>=6.1",
    "flask>=3.1.0",
    "quote",
]

[tool.uv.sources]
quote = { path = "../quote" }
