[project]
name = "c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "a",
    "b"
]

[tool.uv.sources]
a = { path = "../A" }
b = { path = "../B" }
