[project]
name = "A"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MengChiehLiu", email = "jk211896@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25,<3.0",
]